### ISSUE TITLE
Autocompletion not inserting code

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#29] opened 2020-04-23 14:59 UTC
If I type half of a variable name then press Ctrl-Space, it displays a drop down with the full variable name. If I click on it, it doesn't insert the full name in the code.

Also it displays in the commandor "showsourceitems(edit.editpos)".

**Comment by fredvs** [comment] 2020-04-23 16:01
OK, I will check that.

**Comment by fredvs** [comment] 2020-04-23 16:20
>  If I click on it, it doesn't insert the full name in the code.

Ha, yes, indeed, this was the result of hard discussion in MSE mailing list.
At the end Martin does convince us, for him a good ide dont have to touch to code.
Ok to give infos in a list but not to paste code.

Anyway maybe we could thing to add possibility to insert code.
But maybe.

> Also it displays in the commandor "showsourceitems(edit.editpos)".

Hum, sorry, this one I do not catch.
Where in the commandor?

**Comment by circular17** [comment] 2020-04-23 16:28
Well Martin is not obliged to use the code completion.

![image](https://user-images.githubusercontent.com/9092455/80124150-1b6af280-8590-11ea-8f8f-85cbe5d89053.png)

**Comment by fredvs** [comment] 2020-04-23 16:32
Sory but how do you get `showsourceitems(edit.editpos)` in Commandor?

Could you tell the operations you did?
I cannot reproduce it.
(Or maybe you discover something than I never seen).

**Comment by fredvs** [comment] 2020-04-23 16:37
> Also it displays in the commandor "showsourceitems(edit.editpos)".

It is the command used by Shift + Space.
I agree it is not needed, I did use for debugging, thanks to note it, I will remove it.

**Comment by circular17** [comment] 2020-04-23 17:14
Ok.

So I suppose the code completion is not for this release.

Something else though, the list is methods is not formatted (it contains $ symbols):
![image](https://user-images.githubusercontent.com/9092455/80128856-90412b00-8596-11ea-8872-4f8225a81f56.png)

The font is small by the way, which is kind of ok for this one.

**Comment by fredvs** [comment] 2020-04-23 18:01
> So I suppose the code completion is not for this release.
I fear that no for insert (even if I already begin the work).

> Something else though, the list is methods is not formatted (it contains $ symbols):

Yes it is the universal format used by Martin.
I agree if we go foward for code completion, it could be adapted for each prog language.

> The font is small by the way, which is kind of ok for this one.

No, no, no the good news is that the size of the list is sized now with the font height.

**Comment by fredvs** [comment] 2020-04-23 19:02
> If I click on it, it doesn't insert the full name in the code.

OK in next commit if you 2xclick on a item it will be pasted where is the cursor.

**Comment by circular17** [comment] 2020-04-24 07:39
Gonna check that

**Comment by circular17** [comment] 2020-04-24 07:59
> > So I suppose the code completion is not for this release.
> 
> I fear that no for insert (even if I already begin the work).

> OK in commit [035581c](https://github.com/fredvs/ideU/commit/035581c0901d76887f03397496b1925fa94d29f1) : if you 2xclick on a item it will be pasted where is the cursor.

Seems it was possible in fact. I tested it, that's good, though you need to first delete the current word before inserting, like you did with CTRL-T. Otherwise you get repetitions of parts of the word.

> Yes it is the universal format used by Martin.
> I agree if we go foward for code completion, it could be adapted for each prog language.

Hmm to me that's more like an assembler label. Anyway I suggest to format it with brackets and commas, as it is what most languages use. If you ever come across a language that doesn't use that, you can still customize for this language.

Something else: if I press Ctrl-Shift-Space to get info about parameters, it will display the list of procedures in the Pascal format for one second, and then replace the content of the completion drop down with the content for Ctrl-Space.

> No, no, no the good news is that the size of the list is sized now with the font height.

Cool!

**Comment by fredvs** [comment] 2020-04-24 13:33
> Something else: if I press Ctrl-Shift-Space to get info about parameters, it will display the list of > procedures in the Pascal format for one second, and then replace the content of the completion drop down with the content for Ctrl-Space.

Once again, sorry but I cannot reproduce it.
Maybe a video will help.

**Comment by circular17** [comment] 2020-04-24 14:01
Here it is:
![ideu_ctrl_shift_space](https://user-images.githubusercontent.com/9092455/80220946-dead0300-8644-11ea-889e-656f03443886.gif)

I am just pressing Ctrl-Shift-Space once.

**Comment by fredvs** [comment] 2020-04-24 14:08
Could you try this, click on the lamp icon, try the same with both lamp on and off to see if it has something to do with the auto list.

**Comment by circular17** [comment] 2020-04-24 14:16
Indeed, I turned on the lamp and then off again. And now it doesn't display the second list. If I turn back on the lamp, the bug happens.

**Comment by fredvs** [comment] 2020-04-24 14:24
>Indeed, I turned on the lamp and then off again. And now it doesn't display the second list. If I turn > back on the lamp, the bug happens.

OK, I can reproduce it, ok, I will fix it.

> By the way, what is this lamp about?

When on, a list similar to CTRL + space will appear when you are typing, showing all what could be written.

It must be set to pause if using` CTRL + space` or  `CTRL + shift + space` .
I will fix it tonight.

Thanks to note it.

**Comment by circular17** [comment] 2020-04-24 14:57
By the way, the lamp icon is displayed as disabled when the program starts, even if it is enabled.

Other problem, when the completion list appears, if I press a key just at this moment, the input is lost, i.e. the character is not added to the code.

**Comment by fredvs** [comment] 2020-04-24 15:03
OK, I will check this tonight.

**Comment by fredvs** [comment] 2020-04-24 15:35
> By the way, the lamp icon is displayed as disabled when the program starts, even if it is enabled.

Yes, thanks to note it, I forget to enable it after changing icon behavior yesterday, I will fix it tonight.

> Other problem, when the completion list appears, if I press a key just at this moment, the input is > lost, i.e. the character is not added to the code.

Hum, ok, sometime it appends indeed, I will see what can be done.

**Comment by circular17** [comment] 2020-04-24 16:11
> > By the way, the lamp icon is displayed as disabled when the program starts, even if it is enabled.
> Hum, ok, sometime it appends indeed, I will see what can be done, it is because the list take focus just at moment you typed.

Maybe redirect key event?

Note: the word is "it happens" not "it appends". Appending means adding at the end of a list.

**Comment by fredvs** [comment] 2020-04-24 18:15
OK, all should be fixed with commit f6e127c

**Comment by circular17** [comment] 2020-04-24 19:46
That's fine. 

Remains to replace the current word instead of inserting. As I said previously you could do as you did for CTRL-T to remove the word and then insert.

**Comment by fredvs** [comment] 2020-04-24 19:58
> That's fine.
> 
> Remains to replace the current word instead of inserting. As I said previously you could do as you did for CTRL-T to remove the word and then insert.


OK, I will try to do it before to do to bed.
Otherwise it will be for tomorrow.

**Comment by fredvs** [comment] 2020-04-24 20:17
> Remains to replace the current word instead of inserting.

Should be fixed with commit 9787fdf

**Comment by circular17** [comment] 2020-04-24 21:41
Ok we're getting there.

One final suggestion: 

- that the word would not be selected in the end
- and that the completion list would hide when we double click

After that, I guess I have no other suggestion for next release.

Regards

**Comment by fredvs** [comment] 2020-04-24 23:15
>   that the word would not be selected in the end
>   and that the completion list would hide when we double click

Should be fixed in commit 412a07e

**Comment by circular17** [comment] 2020-04-25 07:30
Ok I thought that would be it but when one insert a procedure/function definition, it should either:

- format it, so that we can navigate with Ctrl-ArrowLeft and Ctrl-ArrowRight.
- or insert just the name of the function and one bracket.

**Comment by fredvs** [comment] 2020-04-25 13:40
> Ok I thought that would be it but when one insert a procedure/function definition, it should either:
> 
>     * format it, so that we can navigate with Ctrl-ArrowLeft and Ctrl-ArrowRight.
> 
>     * or insert just the name of the function and one bracket.

I fear that formatting  procedure/function definitions will be for the next release.

;-(

**Comment by circular17** [comment] 2020-04-25 14:31
No problemo

**Comment by fredvs** [comment] 2020-04-26 16:14
> Ok I thought that would be it but when one insert a procedure/function definition, it should either:
> 
>     * format it, so that we can navigate with Ctrl-ArrowLeft and Ctrl-ArrowRight.
> 
>     * or insert just the name of the function and one bracket.

I will see if I find some resource to jump into that tonight.

**Comment by fredvs** [comment] 2020-04-26 22:04
Sorry, I give it up for now.
I dont really catch if you want to paste things from Ctrl+Space or Ctrl+Shift+Space.

**Comment by circular17** [comment] 2020-04-26 22:14
No problemo. Have a good evening/night

**Comment by fredvs** [comment] 2020-04-26 23:51
> insert just the name of the function and one bracket.

In commit 813926b it has this:

When using `Ctrl+Space`, 2xclick on the list inserts just the name and one bracket if there is a '$' symbol.
Otherwise it just inserts the name.

Using `Ctrl+Shift+Space` only gives info, 2xclick is disabled (for the moment).

Maybe we can let it like this for this release.

**Comment by fredvs** [comment] 2020-04-26 23:57
And I even think that adding the bracket is too much and should be added manually.

But that is a very little detail.

Good night and many thanks for your release.

Fre;D

**Comment by circular17** [comment] 2020-04-27 16:02
That's nice. I noticed yet another thing. After doing Ctrl+Space, when I click an item in the autocompletion list, it scrolls down to the bottom, and I end up clicking another item. I suppose this is the case because the last item of the list is selected by default.

**Comment by fredvs** [comment] 2020-04-27 18:32
OK, I will check that.

**Comment by fredvs** [comment] 2020-04-27 20:06
OK, fixed in commit 1cbdca6

Thanks to note it.

**Comment by fredvs** [comment] 2020-04-27 20:16
I am still not sure that adding always a ` '(' `when `'$'` is found is a ok because if it is a class , it should add a '.' .

**Comment by fredvs** [comment] 2020-04-27 22:11
![Sans titre](https://user-images.githubusercontent.com/3421249/80425863-ce1ab800-88e4-11ea-9d7e-71d9dc3fbdbe.png)

**Comment by fredvs** [comment] 2020-04-27 22:21
Done with lamp on.

![video](https://user-images.githubusercontent.com/3421249/80426499-21d9d100-88e6-11ea-844d-d162a8cb9d33.gif)

**Comment by fredvs** [comment] 2020-04-28 16:55
Hello.

In commit d03f42f, the list is formatted in Pascal flavour.

![autocomplete2](https://user-images.githubusercontent.com/3421249/80515055-a6c5f880-8981-11ea-877a-5682c335ded9.png)

![autocomplete3](https://user-images.githubusercontent.com/3421249/80515074-ad547000-8981-11ea-92d8-0f3c0421f1cd.png)

![autocomplete4](https://user-images.githubusercontent.com/3421249/80515087-b47b7e00-8981-11ea-8e48-38e3e524c009.png)

Your advice is welcome!

**Comment by fredvs** [comment] 2020-04-28 18:50
And in commit e284b47:

![autocomplete5](https://user-images.githubusercontent.com/3421249/80525586-c402c300-8991-11ea-880d-c3083459a6ec.png)

OK, now I really stop.

Have lot of fun!

**Comment by circular17** [comment] 2020-04-29 09:16
> ![Sans titre](https://user-images.githubusercontent.com/3421249/80425863-ce1ab800-88e4-11ea-9d7e-71d9dc3fbdbe.png)

Oh so the $ sign was used for "." and for "(". Yeah that's ambiguous.

Looks like you progressed a bit on that, I will have a look.

**Comment by fredvs** [comment] 2020-04-29 11:36
> Oh so the $ sign was used for "." and for "(". Yeah that's ambiguous.

Huh, even more ambiguous...
`application()` is a procedure too!

**Comment by circular17** [comment] 2020-04-29 15:38
Oh ok indeed I saw that. Then it is fair that the autocomplete would add a parenthesis. 

To avoid that, I suppose you could remove the "()" when there are no parameters because anyway it is not necessary in Pascal.

Anyway I think it is quite convenient now.

**Comment by fredvs** [comment] 2020-04-29 16:39
> To avoid that, I suppose you could remove the "()" when there are no parameters because anyway it is not necessary in Pascal.

Are you talking for case like this?

![Sans titre](https://user-images.githubusercontent.com/3421249/80621781-17374d00-8a48-11ea-9386-d52fb422813b.png)

Hum, ok, but, I already receive warnings in uos forum that said that the good usage in Pascal is to use `"()"` if no parameters are used for a procedure or function.

So I did add `"()"` fro each method, for example:

`function Tuos_Init.loadlib(): cint32;`

**Comment by fredvs** [comment] 2020-04-29 16:42
Re-huml, did you try last commit because it should not have problems with methods without parameters.

**Comment by fredvs** [comment] 2020-04-29 16:55
Ok, ok, I get it, you want avoid to oblige people to remove the '()' if they dont want to use a method vs a class.
And the example of `application` is a perfect example.

OK, I will remove the '()'.

**Comment by fredvs** [comment] 2020-04-29 17:13
Sorry, I am back again...

OK, to remove '()' but then also the ';' ?
So, if a method without parameter is added via the auto-complete list, only the name will be added.

Are you ok with the behavior of now, for methods with parameters, all the method with kind of parameters  is added, with the coma, like this?


![video](https://user-images.githubusercontent.com/3421249/80625385-6d5abf00-8a4d-11ea-8893-b56873b16700.gif)

**Comment by circular17** [comment] 2020-04-29 19:07
> OK, to remove '()' but then also the ';' ?
> So, if a method without parameter is added via the auto-complete list, only the name will be added.

Sounds good

> Are you ok with the behavior of now, for methods with parameters, all the methods with kind of parameters is added, with the comas, like this?

Yes. I am not used to it, but it makes sense to me.

**Comment by fredvs** [comment] 2020-04-29 19:14
OK, many thanks for your attention.
I will release it asap.

Huh, sorry to annoy you but there is a issue in msegui that needs your advice.

**Comment by fredvs** [comment] 2020-04-30 17:28
Hello.

> Yes. I am not used to it, but it makes sense to me.

Ok, so let do like this, if `Ctrl+Space` was used, 2xClick will insert, for a method, only `themethod(`

If it was 2XCliked from the auto-list of lamp-icon, all the method with parameter will be added.

I released ideU 2.2.0 : https://github.com/fredvs/ideU/releases

Many, many thanks Johann for all your perfect ideas, bug fixes and kind support.

Fre;D

**Closed** 2020-05-19 23:02 UTC
